name: Greeting on variable day
on: [push]
env:
  DAY_OF_WEEK: Monday
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy
      



