name: Greeting on variable day
on: [push]
env:
  DAY_OF_WEEK: Monday
jobs:
  premier_job :
    runs-on : ubuntu-latest
    steps :
      - name : définir une sortie
        id : etape1
        run : echo "output_var=Bonjour" >> $GITHUB_OUTPUT
    outputs :
      ma_sortie : ${{ steps.etape1.outputs.output_var }}

  deuxieme_job :
    needs : premier_job
    runs-on : ubuntu-latest
    steps :
      - name : utiliser la sortie du premier job
        run : echo "La valeur de la sortie du premier job est ${{ needs.premier_job.outputs.ma_sortie }}"


