name: Greeting on variable day
on: [push]
env:
  DAY_OF_WEEK: Monday
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    - name: "Say Hello Mona it's Monday"
      env:
        First_Name: Mona
      run: |
        echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        echo VAR_4: $VAR_4
        echo SECRET_1: $SECRET_1
